### ISSUE TITLE
Configuration Override Problems with SilverStripe 4.1

### ISSUE THREAD

**Issue by gordonbanderson** [silverstripe/silverstripe-comments#242]
I am currently unable to alter the default configuration in order to force moderation of comments and see toggles for this in the CMS.

Steps
1) Install SS 4.1 using composer as per normal.
2) Install the comments module - `composer require silverstripe/comments dev-master` (note that dev-master is required as the current tagged version is broken with 4.1)

When I try and override configuration as below, in mysite/_config/comments.yml, the values used by the CommentsExtension are those hardwired into the module PHP.

This is as per the docs, but stripped down for clarity:
```
SilverStripe\CMS\Model\SiteTree:
 comments:
   require_moderation: true
   use_gravatar: true # set to true to show gravatar icons,
   gravatar_size: 80 # size of gravatar in pixels.  This is the same as the standard default
   gravatar_default: 'identicon' # theme for 'not found' gravatar (see http://gravatar.com/site/implement/images/)
   gravatar_rating: 'g' # gravatar rating. This is the same as the standard default
   require_login_cms: true
   require_moderation_cms: true

```

@andante on IRC suggested adding an after clause, this has the same lack of effect though :(

```
---
Name: suilvencomments
After:
  - '#commentssitetree'
---
SilverStripe\CMS\Model\SiteTree:
 comments:
   require_moderation: true
   use_gravatar: true # set to true to show gravatar icons,
   gravatar_size: 80 # size of gravatar in pixels.  This is the same as the standard default
   gravatar_default: 'identicon' # theme for 'not found' gravatar (see http://gravatar.com/site/implement/images/)
   gravatar_rating: 'g' # gravatar rating. This is the same as the standard default
   require_login_cms: true
   require_moderation_cms: true
---
```

I flushed at each of the command line, public view and admin views.  No effect.  Logging using error_log shows that the hardwired values are used, ie the configuration has no effect.

As an extra test I turned on gravatars by altering the `use_gravatar` variable in CommentsExtension as below.

```
private static $comments = [
        'enabled' => true,
        'enabled_cms' => false,
        'require_login' => false,
        'require_login_cms' => false,
        'required_permission' => false,
        'include_js' => true,
        'use_gravatar' => true, // << this is the change
```

After running `sake dev/build` and flushing the public page, gravatars are showing.

It is of course possible that I am doing something wrong, if so apologies, but a working example of auto force moderation of comments would be good :)

**Comment by dhensby** [comment]
> (note that dev-master is required as the current tagged version is broken with 4.1)

Try using `^3.1` for the safest way to require a working version

**Comment by dhensby** [comment]
for clarity, you are adding this part, yes?

```yml
SilverStripe\CMS\Model\SiteTree:
  extensions:
    - SilverStripe\Comments\Extensions\CommentsExtension
```

**Comment by gordonbanderson** [comment]
Regarding the above clarity query, yes I am using that YML to instantiate the CommentsExtension, as per docs/en/Configuration.md, and I am seeing a comments form being rendered.  It's the properties under the comments section of that document that I cannot get to work, ie to override.

**Comment by gordonbanderson** [comment]
Regarding the above clarity query, yes I am using that YML to instantiate the CommentsExtension, as per docs/en/Configuration.md, and I am seeing a comments form being rendered.  It's the properties under the comments section of that document that I cannot get to work, ie to override.

Going minimal, I tried this:
```
SilverStripe\CMS\Model\SiteTree:
  comments:
    use_gravatar: true
```

Gravatars *do not* show in the public interface.  If I override in CommentsExtension then I see the gravatars.


The above is with ^3.1 as suggested, SilverStripe 4.1, PHP 7.2

**Comment by dhensby** [comment]
Right, @gordonbanderson I've had time to look into this and I think there's a bug in the way framework merges configs.

At the moment configs can come from 1 of 3 sources:
- yaml
- `private static`
- run time modifications

The problem that I've found is that the `private static` definition coming from `Extension` instances are being merged into the config than a higher priority that those that are already defined by yaml or PHP classes, which renders any of the changes in our yaml or classes ineffective.

I've opened an issue against framework: https://github.com/silverstripe/silverstripe-framework/issues/7970

**Comment by gordonbanderson** [comment]
Thanks for confirming that I was not going crazy :)  And also thanks for your time looking into this, appreciated.

**Comment by tractorcow** [comment]
I've had a look at the issue and suggested solution. I have a suggestion of my own that requires no API convention changes on the part of framework.

https://github.com/silverstripe/silverstripe-framework/pull/7971#issuecomment-378463301

Relevant comment:

> I respect that silverstripe/silverstripe-comments#242 is an issue, but I don't think flipping the core convention at this point in time is a fair solution to this.

> A better solution is to change the config provided by the extension to a separate key, e.g.
```php
private static $comments_defaults = [
]
```

> And ensuring that getCommentsOptions did a recursive merge of $config->get('comments') and $config_>get('comments_defaults') to respect user-assigned values over the provided defaults.

**Comment by robbieaverill** [comment]
Yeah I agree with @tractorcow's approach to be honest. The way this part of the comments config works has caused my team troubles in the past and it's a little less standard than other CWP modules use of the config API. I think simplifying it would be a good idea.

**Comment by robbieaverill** [comment]
Relevant problem with this code in the recent past: https://github.com/silverstripe/silverstripe-framework/pull/7390

**Comment by tractorcow** [comment]
Oh, also, you can apply your YML Config to the extension directly and it will override.

```yaml
SilverStripe\Comments\Extensions\CommentsExtension:
  comments:
    require_moderation: true
```

If you need to get up and running in the mean time ;)

**Comment by robbieaverill** [comment]
More discussion with @tractorcow:

* configuration merging order is (least to highest priority): statics -> YAML -> extensions -> modifications
* statics and YAML are merged together, you can't decorate between them (either before or after both)
* if we follow @tractorcow's suggested approach then we don't actually need to override the defaults at all, we just merge custom config into the defaults (solves this problem)
* we then don't need to change framework behaviour or lock to a specific version of framework for this bug

**Comment by micobarac** [comment]
Changing extension's original `*.yml` config is not a good way of changing things. Creating a custom `*.yml` config inside `mysite/_config` should be the way of doing things, which isn't working right now.

**Comment by robbieaverill** [comment]
I think this needs to be retested now that https://github.com/silverstripe/silverstripe-framework/pull/7971 has been merged into 4.0.x. If that pull request fixes this issue then we should close this issue.

**Comment by robbieaverill** [comment]
I've re-tested this, and believe it's resolved now by https://github.com/silverstripe/silverstripe-framework/pull/7971.

Testing on:

* silverstripe/recipe-cms: 4.2.0
* silverstripe/blog: 3.2.0
* silverstripe/comments: 3.1.0

Example config in `app/_config/comments.yml`:

```yaml
SilverStripe\Blog\Model\Blog:
  extensions:
    - SilverStripe\Comments\Extensions\CommentsExtension
  comments:
    enabled: false

SilverStripe\Blog\Model\BlogPost:
  extensions:
    - SilverStripe\Comments\Extensions\CommentsExtension
  comments:
    enabled: true
    frontend_moderation: true
    require_moderation_nonmembers: true
    require_moderation_cms: true
    require_login: false
    require_login_cms: true
    nested_comments: true
    order_comments_by: '"Created" ASC'
```

Test steps:

* Log into CMS
* Create a Blog
* Create a BlogPost underneath it
* Go to the frontend, open the new Blog, check whether comments are enabled (should not be)
* Open the new BlogPost in this blog, check whether comments are enabled (should be)

Results:

* silverstripe/recipe-cms: 4.1.0 ❌ 
* silverstripe/recipe-cms: 4.2.0 ✅ 

Closing as resolved in core. The fix is to update your version of SilverStripe core to 4.2.0 or newer, however since https://github.com/silverstripe/silverstripe-framework/pull/7971 was merged into the 4.0 branch, this fix may also become available in the future 4.0 and 4.1 core release lines.

Thanks to everyone for their patience with this issue!
