### ISSUE TITLE
'use_preview' => true - doesn't seem to work

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-comments#281]
**Comments 3.2.x-dev**

Not sure if this was supposed to do an AJAX request to get a rendered comment preview or something, but all it does now is render an empty field on the frontend:

![image](https://user-images.githubusercontent.com/5170590/56941020-d7543600-6b65-11e9-9931-27c96675a501.png)

Nothing in the JS console.

**Comment by NightJar** [comment]
```yml
    html_allowed: false # allow for sanitized HTML in comments
    html_allowed_elements:
      - a
      - img
      - i
      - b
    use_preview: false # preview formatted comment (when allowing HTML). Requires include_js=true
```
Indicates that HTML is disabled by default, and is required for the preview.
Arguably the `use_preview` setting should be ignored if `html_allowed` is `false`.

https://github.com/silverstripe/silverstripe-comments/blob/e21a09234a3070d3c869218739c9d45f168ced41/src/Forms/CommentForm.php#L97

The above however indicates that the assumption of AJAX is correct, and https://github.com/silverstripe/silverstripe-comments/blob/3812057b0075cf37fccc5111fa35b5a754aa6031/javascript/CommentsInterface.js contains no reference to `preview` at all.
